#base   "../../../../../../cfg/hud_player_model.txt"
#base   "../../../../../../cfg/hud_spy_disguise.txt"
#base	"../../_customizations/speedometer/speedometer.res"
#base	"../../_fixes/resource/ui/hudplayerclass.res"
#base	"../../_tf2hud/resource/ui/hudplayerclass.res"